version: '3'

services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=caddy_manager
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
      - "2019:2019"  # API Caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config

volumes:
  postgres-data:
  caddy-data:
  caddy-config: